### ISSUE TITLE
[kube-router] some configuration fields are not implemented in the template

### ISSUE THREAD

**Issue by abuisine** [enix/helm-charts#32]
```
kubeRouter:
  router:
    routesSyncPeriod: 1m0s
  metrics:
    port: "9999"
```
does not change anything to the resulting resource
