### ISSUE TITLE
[netbox] LDAP does not work anymore with 1.2.9

### ISSUE THREAD

**Issue by mscbpi** [enix/helm-charts#40]
A working LDAP configuration with Active Directory does not work anymore when upgrading to 1.2.9

Rollback to 1.2.8 and it works again.

**Comment by mscbpi** [comment]
docker image *-ldap has a miss : https://github.com/netbox-community/netbox-docker/issues/324

it does not include necessary configuration in `configuration.py`.
```
REMOTE_AUTH_ENABLED="true"
REMOTE_AUTH_BACKEND="netbox.authentication.LDAPBackend"
AUTH_USER_MODEL="auth.User"
```
workaround:
create a `ConfigMap` and mount it as `extraVolumeMounts` in `values.yaml`.
```
extraVolumes: 
 - name: netbox-test-config 
   configMap:
    defaultMode: 420
    name: netbox-test-config
   
   
extraVolumeMounts: 
 -  name: netbox-test-config
    mountPath: /etc/netbox/config/configuration.py
    subPath: configuration.py
```
