### ISSUE TITLE
Request LDAP image support for netbox

### ISSUE THREAD

**Issue by iWangJiaxiang** [enix/helm-charts#5]
Thank you for the chart, could you add support for LDAP image for netbox?

**Comment by Zempashi** [comment]
Hey, thanks for your interest in our chart ;)

The README lacks some guidance for ldap, indeed...
But this could be achievable without any chart modification.
You just need to override image to put the version you prefer + `-ldap`, then to follow https://github.com/netbox-community/netbox-docker/wiki/LDAP as well as the main Netbox documentation. Put configuration variables in `extraEnvs` and password variables in `extraSecretEnvs`.

Something like:
```
image:
  tag: v2.8.1-ldap
extraEnvs:
  AUTH_LDAP_SERVER_URI: "ldaps://domain.com"
  AUTH_LDAP_BIND_DN: "CN=Netbox,OU=EmbeddedDevices,OU=MyCompany,DC=domain,dc=com"
  AUTH_LDAP_USER_SEARCH_BASEDN: "OU=MyCompany,DC=domain,dc=com"
  AUTH_LDAP_GROUP_SEARCH_BASEDN: "OU=SubGroups,OU=MyCompany,DC=domain,dc=com"
  AUTH_LDAP_REQUIRE_GROUP_DN: "CN=Netbox-User,OU=SoftwareGroups,OU=SubGroups,OU=MyCompany,DC=domain,dc=com"
  AUTH_LDAP_IS_ADMIN_DN: "CN=Network Configuration Operators,CN=Builtin,DC=domain,dc=com"
  AUTH_LDAP_IS_SUPERUSER_DN: "CN=Domain Admins,CN=Users,DC=domain,dc=com"
  LDAP_IGNORE_CERT_ERRORS: "false"
extraSecretEnvs:
  AUTH_LDAP_BIND_PASSWORD: "TopSecretPassword"
```
