### ISSUE TITLE
I am unable to find the prometheus rules

### ISSUE THREAD

**Issue by ws-prive** [enix/helm-charts#69]
Hi,

I have installed the helm with:
```
helm repo add enix https://charts.enix.io
helm repo update

NAMESPACE="x509-certificate-exporter"

helm upgrade x509-certificate-exporter enix/x509-certificate-exporter -f monitor-host-values.yaml \
    --install \
    --create-namespace \
    --namespace ${NAMESPACE}
```

The monitor-host-values.yaml contains:
```
hostPathsExporter:
  daemonSets:
    cp:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      watchFiles:
      - /var/lib/kubelet/pki/kubelet-client-current.pem
      - /etc/kubernetes/pki/apiserver.crt
      - /etc/kubernetes/pki/apiserver-etcd-client.crt
      - /etc/kubernetes/pki/apiserver-kubelet-client.crt
      - /etc/kubernetes/pki/ca.crt
      - /etc/kubernetes/pki/front-proxy-ca.crt
      - /etc/kubernetes/pki/front-proxy-client.crt
      - /etc/kubernetes/pki/etcd/ca.crt
      - /etc/kubernetes/pki/etcd/healthcheck-client.crt
      - /etc/kubernetes/pki/etcd/peer.crt
      - /etc/kubernetes/pki/etcd/server.crt
      watchKubeconfFiles:
      - /etc/kubernetes/admin.conf
      - /etc/kubernetes/controller-manager.conf
      - /etc/kubernetes/scheduler.conf
    nodes:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ingress
        operator: Exists
      watchFiles:
      - /var/lib/kubelet/pki/kubelet-client-current.pem
      - /etc/kubernetes/pki/ca.crt
```

But I am unable to find the Prometheus rules. there is nothing in Prometheus (rules or alerts) with *x509*. I am running Kube-Prometheus-Stack 20.0.1 (Helm) with K8s 1.22.2

Can you help me out with this? Thanks!
