### ISSUE TITLE
Add Support for Custom Labels to cnpg-cluster

### ISSUE THREAD

**Issue by florianspk** [enix/helm-charts#84]
# Description
A new feature is being implemented to allow users to define custom extra labels for resources via the labels field in the Helm chart. These labels can be used to tag resources for organizational or operational purposes.
# Example Usage in values.yaml
```yaml
labels:
  app.kubernetes.io/name: monkey-cluster
  app.kubernetes.io/instance: monkey-moon
  env: production
  ```
